'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ProxyScraper.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to $http://aliveproxy.com/anonymous-proxy-list
        '''$http://aliveproxy.com/ca-proxy-list
        '''$http://aliveproxy.com/de-proxy-list
        '''$http://aliveproxy.com/fastest-proxies
        '''$http://aliveproxy.com/fr-proxy-list
        '''$http://aliveproxy.com/gb-proxy-list
        '''$http://aliveproxy.com/high-anonymity-proxy-list
        '''$http://aliveproxy.com/jp-proxy-list
        '''$http://aliveproxy.com/proxy-list-port-3128
        '''$http://aliveproxy.com/proxy-list-port-80
        '''$http://aliveproxy.com/proxy-list-port-8000
        '''$http://aliveproxy.com/proxy-list-port-8080
        '''$http://a [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property psrc() As String
            Get
                Return ResourceManager.GetString("psrc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.2 Safari/537.36.
        '''</summary>
        Friend ReadOnly Property UserAgent() As String
            Get
                Return ResourceManager.GetString("UserAgent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://pastebin.com/raw/KhiFJE4m.
        '''</summary>
        Friend ReadOnly Property WebSrc() As String
            Get
                Return ResourceManager.GetString("WebSrc", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
