'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ProxyGenerator.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        '''/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\ PROXY GENERATOR v2.5 /\/\/\/\/\/\/\/\/\/\/\/\/\/\
        ''' /\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\ BY ERIC904P /\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\
        '''++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        '''- - - - - - - - - - - - - - - -CHECKING PLEASE WAIT- - - - - - - - - - - - - - -
        '''++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++.
        '''</summary>
        Friend ReadOnly Property CheckHeader() As String
            Get
                Return ResourceManager.GetString("CheckHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to http://azenv.net.
        '''</summary>
        Friend ReadOnly Property Judge() As String
            Get
                Return ResourceManager.GetString("Judge", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        '''/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\ PROXY GENERATOR v2.5 /\/\/\/\/\/\/\/\/\/\/\/\/\/\
        ''' /\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\ BY ERIC904P /\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\
        '''++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        '''- - - - - - - - - - - - - - - -PRESS ENTER TO START- - - - - - - - - - - - - - -
        '''++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++.
        '''</summary>
        Friend ReadOnly Property MainHeader() As String
            Get
                Return ResourceManager.GetString("MainHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ProxyGenCheck_.
        '''</summary>
        Friend ReadOnly Property PGC_() As String
            Get
                Return ResourceManager.GetString("PGC_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ProxyGenScrape_.
        '''</summary>
        Friend ReadOnly Property PGS_() As String
            Get
                Return ResourceManager.GetString("PGS_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to $http://50kproxies.com/10-february-10-02-new-fresh-daily-50000-proxy-list-50kproxies-com/
        '''$http://50kproxies.com/11-january-11-01-new-fresh-daily-50000-proxy-list-50kproxies-com/
        '''$http://50na50.net/
        '''$http://50na50.net/proxy/httplist
        '''$http://50na50.net/no_anonim_http.txt
        '''$http://aliveproxy.com/anonymous-proxy-list
        '''$http://aliveproxy.com/ca-proxy-list
        '''$http://aliveproxy.com/de-proxy-list
        '''$http://aliveproxy.com/fastest-proxies
        '''$http://aliveproxy.com/fr-proxy-list
        '''$http://aliveproxy.com/gb-proxy-list        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property psrc() As String
            Get
                Return ResourceManager.GetString("psrc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        '''/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\ PROXY GENERATOR v2.5 /\/\/\/\/\/\/\/\/\/\/\/\/\/\
        ''' /\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\ BY ERIC904P /\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\
        '''++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        '''- - - - - - - - - - - - - - - -SCRAPING PLEASE WAIT- - - - - - - - - - - - - - -
        '''++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++.
        '''</summary>
        Friend ReadOnly Property ScrapeHeader() As String
            Get
                Return ResourceManager.GetString("ScrapeHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HTTP_HOST = azenv.net.
        '''</summary>
        Friend ReadOnly Property TestString() As String
            Get
                Return ResourceManager.GetString("TestString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/29.0.1547.2 Safari/537.36.
        '''</summary>
        Friend ReadOnly Property UserAgent() As String
            Get
                Return ResourceManager.GetString("UserAgent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please wait until program is finished..
        '''</summary>
        Friend ReadOnly Property v2_Threading_SaveFile_Please_wait_until_program_is_finished_() As String
            Get
                Return ResourceManager.GetString("v2_Threading_SaveFile_Please_wait_until_program_is_finished_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to txt files (*.txt)|*.txt.
        '''</summary>
        Friend ReadOnly Property v2_Threading_SaveFile_txt_files____txt____txt() As String
            Get
                Return ResourceManager.GetString("v2_Threading_SaveFile_txt_files____txt____txt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  proxies found at .
        '''</summary>
        Friend ReadOnly Property v2_Threading_ScrapeLink__proxies_found_at_() As String
            Get
                Return ResourceManager.GetString("v2_Threading_ScrapeLink__proxies_found_at_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to https://pastebin.com/raw/KhiFJE4m.
        '''</summary>
        Friend ReadOnly Property WebSrc() As String
            Get
                Return ResourceManager.GetString("WebSrc", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
